### ISSUE TITLE
Alpha 0.1.0 checklist

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Solve4x#26]
Previously the 0.1.0 milestone had a nice markdown checklist. Then GitHub changed how they render milestones and the list broke. Hence I have copied milestone 0.1.0 verbatim below:

---

Basic solving functionality with a basic GUI. Needs to be able to solve and explain most first degree equations, and simplify and factor first degree expressions.

- [ ] Solver with basic support for first degree equations and expressions [underway]
  - [x] Core parser/solver
    - [x] Equations
    - [x] Expressions
    - [x] Terms
    - [x] Mixed numbers
    - [x] Fractions
    - [x] Numbers
    - [x] Roots
    - [x] Variables
  - [ ] Set of solving algorithms [underway]
    - [x] Add, subtract, multiply, and divide
      - [x] Add/subtract (combine like terms)
      - [x] Multiply
      - [x] Divide by canceling factors
    - [x] Undo addition, subtraction, multiplication, and division
      - [x] Undo addition/subtraction (add/subtract from both sides)
      - [x] Undo multiplication (divide both sides)
      - [x] Undo division (multiply both sides)
    - [ ] Work with fractions
      - [ ] Find LCD for fractions (prepare to add/subtract them)
      - [ ] Multiply fractions
      - [x] Divide fractions (invert and multiply)
    - [ ] Distributive property [underway]
      - [x] Distribute expressions (e.g. `2(x+6)`)
      - [ ] Factor expressions
    - [ ] Ending operations (those that are avoided until the end of solving for accuracy reasons)
      - [ ] Raise to a power (exponents)
      - [ ] Take nth root (square root, cube root, etc.)
      - [x] Divide decimals
      - [x] Convert improper fractions to mixed numbers
  - [x] Equation validator
- [ ] UI
  - [ ] Basic GUI for solving equations [started]
  - [ ] Simple CLI
- [x] Basic equation renderer

---

This issue will be used to tracker further progress on the milestone, due to better Markdown support.
